logging:
#  file:
#    name: app.log
  level:
    org:
      hibernate:
        SQL: DEBUG
        tool:
          hbm2ddl: DEBUG
server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param
  port: ${SERVER_PORT}
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL:jdbc:h2:mem}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    hikari:
      maximum-pool-size: 10
  jpa:
    database: ${JPA_DATABASE}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  application:
    name: taskbasket
